name: Post Tweet Thread

on:
  push:
    paths:
      - "tweets/*.md"

jobs:
  tweet-thread:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install tweepy markdown

    - name: Parse and post tweet thread
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
      run: |
        import os, tweepy

        key = os.environ['TWITTER_API_KEY']
        secret = os.environ['TWITTER_API_SECRET']
        token = os.environ['TWITTER_ACCESS_TOKEN']
        token_secret = os.environ['TWITTER_ACCESS_SECRET']

        auth = tweepy.OAuth1UserHandler(key, secret, token, token_secret)
        api = tweepy.API(auth)

        for file in os.listdir("tweets"):
            if file.endswith(".md"):
                with open(f"tweets/{file}") as f:
                    lines = [line.strip() for line in f if line.strip() and not line.startswith("#")]
                first = api.update_status(lines[0])
                reply_to = first.id
                for tweet in lines[1:]:
                    reply_to = api.update_status(tweet, in_reply_to_status_id=reply_to, auto_populate_reply_metadata=True).id
