- name: Post tweet thread
  run: |
    pip install tweepy markdown

    python3 - <<EOF
import tweepy
import os

auth = tweepy.OAuth1UserHandler(
    os.environ["TWITTER_API_KEY"],
    os.environ["TWITTER_API_SECRET"],
    os.environ["TWITTER_ACCESS_TOKEN"],
    os.environ["TWITTER_ACCESS_SECRET"]
)
api = tweepy.API(auth)

with open("tweets/2025-05-10_firewall_breach.md", "r") as f:
    thread = f.read().split("\n\n")

first = api.update_status(status=thread[0])
reply_to = first.id
for tweet in thread[1:]:
    post = api.update_status(status=tweet, in_reply_to_status_id=reply_to, auto_populate_reply_metadata=True)
    reply_to = post.id
EOF
